### ISSUE TITLE
RFC - Bleve v1.0.0 and Go Modules

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1350]
The Bleve project achieved wide adoption prior to the introduction of Go modules.  As a result, the Bleve team has been careful to not introduce breaking changes.  However, now that Go modules have matured, the community has made it clear that the Bleve project should also adopt them.

While evaluating this change, we determined that this was also the right time to use Go modules to address an important shortcoming in Bleve.  Specifically, Bleve has been limited to a single file format version within a given build.  This is a critical limitation for applications which need to offer backwards compatibility to their end users.  This set of changes leverages Go modules to address this issue.

**NOTE: This proposal will end support for GOPATH builds of bleve and related projects inside the blevesearch organization on github.**

### Support Go Modules

On the surface, this can appear as simple as adding a `go.mod` file to the project.  However, when combined with the other changes below, adopting Go modules really requires you to reevaluate all of your dependencies.

Review the proposed changes to [blevesearch/bleve](https://github.com/blevesearch/bleve/pull/1342)

### Breakout Zap into separate Module

Bleve has an indexing scheme named `scorch`, and scorch was designed to work with different segment implementations.  As of today there is just a single implementation named `zap`.  Zap was also designed to have a version number, so that the file format could evolve over time.  Unfortunately, although the segment abstraction was put in place, the code was physically nested inside the same repository.  This meant that supporting more than one version at a time would either require if/else logic or copy/paste large sections of code, neither of which would be easy to maintain over time.

The much cleaner alternative was to promote `zap` to become its own module.  This allows us to use major versions to delineate incompatible changes with the file format, and use standard git branching and tagging to develop new versions.

The version of `zap` used in Bleve today is `11` and has been moved to it's own repo here: 

[zap v11.0.1](https://github.com/blevesearch/zap/tree/v11.0.1)

### Multiple Versions of Zap supported

A newer version of `zap` which offers significant space savings is introduced as `12` and this code now exists here:

[zap v12.0.1](https://github.com/blevesearch/zap/tree/v12.0.1)

As mentioned in the previous section, by having `zap` as its own module, and by releasing major versions when the file format changes, it becomes straightforward for Bleve's `scorch` index scheme to import multiple `zap` versions into a single build.  This allows Bleve to introduce a new file format `zap v12` which provides significant space savings.  Crucially, an application can start leveraging this new format, while not giving up the ability to read the previous format.

The Bleve project will make decisions about which versions to support, and these will be documented/communicated (see details about Bleve versioning below).

In addition, we understand that advanced users may wish to override scorch's supported segment types and versions.  To do this we provide the following API:

```
func RegisterPlugin(plugin segment.Plugin, makeDefault bool)
func ResetPlugins()
```

**NOTE**: These methods must be called during init() and not used beyond that point.

### Release v1.0.0

The proposal is to declare the current Bleve API, and supported file formats `v1.0.0`.  Many users have adopted Bleve already, and introducing any significant changes at this point would be disruptive.

This includes the following:

- `bleve.New()` will continue to default to the `upsidedown` index scheme.  This is no longer recommended for use, but changing the default would break many existing applications.  We do have plans to change this in the future, but that is outside the scope of this document.
- `bleve.NewUsing()` which requests a `scorch` index will continue to default to the `v11` version of `zap`.  Again, this will change in the future, but ensures maximum compatibility for existing applications.

Because of this, applications wishing to take advantage of the new version of zap must explicitly opt-in to it's usage with additional index configuration:

```
"forceSegmentType": "zap",
"forceSegmentVersion": 12
```

Again, these decisions have been made for maximum compatibility with existing applications.  By adopting Go modules, we make it possible for us to more clearly communicate these types of changes in the future.

### Command-line Tools for Zap

Previously the `bleve` command-line tool included a sub-command `zap` to investigate the details of a zap segment.  This functionality is now available through a dedicated `zap` command in the `blevesearch/zap` repositories.  This allows you to build a version of the zap command that works with corresponding version.

In the future, we may decide to reintroduce this functionality to the main `bleve` command, but for now this is not included.

### Discontinue support for GOPATH builds of Bleve

Attempting to build Bleve, or an application using Bleve without Go modules will result in a compilation error.  This is due to Bleve now having dependency on two major versions of the zap module.  The following options are available:

1.  Upgrade to Go modules.  We understand that this may not be so simple, but we strongly encourage you to consider it, and reach out for help if needed.

2.  We will create a final release tag of Bleve prior to this change `v0.9.0`.  If you're using a tool like govendor, you may simply be able to point to this tag.  Otherwise, you may find the best option is to create a fork of repository and align the master branch on this fork with the tag we've created.  Then, by using a tool such as [govers](https://github.com/rogpeppe/govers) or [sed](https://www.gnu.org/software/sed/manual/sed.html), rewrite the imports in your application from `blevesearch/bleve` to `yourfork/bleve`.

For a period of 6 months, we will ensure that critical bugs are fixed and released on the `v0.9.x` line.

## Take these Changes for a Test Drive

We have been developing these changes on a fork of Bleve (and associated repos) under the [Bluge Labs](https://blugelabs.com) organization.  Our expectation is that users can more easily test these changes by simply adjusting their import path from `github.com/blevesearch/bleve` to `github.com/blugelabs/bleve`.  This repository is not identical, but differs in the following minor ways:

1. Regular development has proceeded on `blevesearch/bleve` however there are no changes we consider major.
2. Because we were still learning Go modules during development there are many more minor versions released `1.0.1`, `1.0.2`, etc.  However, the major versions will be the same in the proposed changes to Bleve (v1.x) and Zap (v11.x and v12.x)

The Bluge Labs organization also contains a version of the [beer-search](https://github.com/blugelabs/beer-search) sample application.  This version of `beer-search` also has a new flag `-forceVersion` which can be used to demonstrate the multiple versions of zap.

If you encounter issues using the Bluge Labs fork, we ask you to please let us know (see the Feedback section)

## Feedback

Your feedback is essential to us moving forward in a way that benefits the entire Bleve community.

### Thumbs Up/Down

You can react to this issue with a basic thumbs up or down.  This can give us a sense of how well this proposal is received.  However, if you give a thumbs down, we ask that you also provide a comment expanding on your thoughts.

### Comment

Please comment on this issue.  We may not be able to satisfy everyone but we can only address the concerns that are shared with us.

### Timeline

We ask that you provide feedback as soon as possible.  We would like to merge these changes by April 3rd, but are willing to adjust the schedule if significant issues are found

## Additional Information on Bleve Versioning

Go modules requires that modules use [Semantic Versioning](https://semver.org/).

Semantic Versioning requires that you increment the MAJOR verison when you `make incompatible API changes`.

It is perhaps obvious that anything which would break compilation would be considered an incompatible API change, however we also feel it should include any incompatible changes to the files created by Bleve.  Users have an expectation that files created by Bleve can be read back in, therefore any time this changes we also plan to increment the MAJOR version number.

Related to this, anytime the default behavior changes (say in the future from upsidedown to scorch), this should also be communicated by incrementing the MAJOR version number. 

## TODO

We plan to work on these items while this issue is reviewed, but some of them may not be completed until after the merge:

- [ ] Fix and/or Setup CI for all repositories
- [ ] Review all repositories in blevesearch organization
- [ ] Archive any repositories which will be no longer maintained
- [ ] If not archiving, tag a final `v0.x` version as is, add go.mod and tag as `v1.0.0`
- [ ] Update go.mod in the PR to reflect newly tagged versions in related repos (vellum, segment, etc) 

### Why did you make `zap` its own repository, Go modules support having multiple modules in the same repository using a naming convention for tags?

We envision that Bleve may ultimately be broken up into several more modules, and that having a single repository with this many modules would be come unwieldy.

### I looked at the go.mod in the blevesearch/bleve PR, and in the blevesearch/zap repos, and it seems like they both depend on each other.  How can that be?

Go modules actually allows for circular dependencies for modules, provided the underlying packages still do not contain a circular dependency.

That said, we still find this undesirable for several reasons, most importantly that when we release a Bleve v2.x we will break all the existing zap plugins for scorch.  We explored adressing this issue now, but found the changes too large and most existing applications would have been broken.

We feel making these larger changes in a v2.x or beyond is more appropriate, as we can leverage the MAJOR version number to more clearly communicate the scope of changes to end users.

### Why have you chosen to implement these changes in a way that breaks GOPATH builds?

We spent considerable time trying to avoid this, and as recently as a week ago, thought we had a clever solution to avoid it, but ultimately it was not possible.

The proposed solution does not yet introduce a `v2` of bleve, but does rely on multiple major versions of zap `v11` and `v12`.  Further, we envision that in the near future, a deeper reorganization of Bleve will introduce a `v2`.  This leads to what is often referred to as the `v2+` problem.  

As described in [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules) the recommended strategy is to develop `v2+` modules in a subdirectory.  

For large projects like Bleve, this seems almost ridiculous to consider.  At this time the Bleve repository has over 600 files, having a second copy under a `v2` folder would be an unacceptable inconvenience for developers.  One could argue that Bleve never should have gotten this large in the first place, but here we are, and refactoring that would result in an even larger breaking change.

Could we have applied this technique to the `v11` folder in zap?  Possibly, but we expect that further versions of zap, or the introduction of Bleve `v2` would ultimately lead to the same ending.

We also considered continuing development of Bleve and other modules on branches other than master, so that `go get` could continue to work with the master branch for GOPATH based development.  But ultimately we concluded this creates too much long term negative impact for the the developers of Bleve.

Based on this, we feel now is the right time to make this incompatible change.

**Comment by mschoch** [comment]
Thank you all for your feedback.  We have not received any negative feedback on this proposal, and we feel confident moving forward.

This weekend, we will be executing the plan.  We hope this goes smoothly, but please understand that due to some circular dependencies, you may notice some temporary issues.  All repos will be tagged prior to making changes.

Our hope is that all everything is resolved by Monday morning at the latest.  If you encounter problems, do not hesitate to open an issue.

**Comment by nebuxadnezzar** [comment]
here is a go.mod in bleve folder

`cat /home/pi/go/src/github.com/blevesearch/bleve/go.mod
module github.com/blevesearch/bleve/v2

go 1.13

require (
	github.com/RoaringBitmap/roaring v0.4.23
	github.com/blevesearch/bleve_index_api v1.0.0
	github.com/blevesearch/go-porterstemmer v1.0.3
	github.com/blevesearch/scorch_segment_api/v2 v2.0.1
	github.com/blevesearch/segment v0.9.0
	github.com/blevesearch/snowballstem v0.9.0
	github.com/blevesearch/upsidedown_store_api v1.0.1
	github.com/blevesearch/vellum v1.0.3
	github.com/blevesearch/zapx/v11 v11.2.0
	github.com/blevesearch/zapx/v12 v12.2.0
	github.com/blevesearch/zapx/v13 v13.2.0
	github.com/blevesearch/zapx/v14 v14.2.0
	github.com/blevesearch/zapx/v15 v15.2.0
	github.com/couchbase/moss v0.1.0
	github.com/golang/protobuf v1.3.2
	github.com/kljensen/snowball v0.6.0
	github.com/rcrowley/go-metrics v0.0.0-20190826022208-cac0b30c2563
	github.com/spf13/cobra v0.0.5
	github.com/steveyen/gtreap v0.1.0
	github.com/syndtr/goleveldb v1.0.0
	github.com/willf/bitset v1.1.10
	go.etcd.io/bbolt v1.3.5
	golang.org/x/text v0.3.0
)
`
So go.mod is there but bleve still complains that it cannot find zapx.
At this point I have no idea how to compile it.
maybe should look at some kind of alternative...
